### ISSUE TITLE
Flash

### ISSUE THREAD

**Issue by squm** [DroidsOnRoids/GlideSharedTransition#1]
are you able to see navigation, status bar, and toolbar flashing/flickering ?

**Comment by Nonda95** [comment]
Yes, it's because for other views is applied fade transition by default. You can exclude these elements from transition by setting customized enter transition for DetailsActivity like this:
```
window.enterTransition = Fade().apply {
    excludeTarget(android.R.id.statusBarBackground, true)
    excludeTarget(android.R.id.navigationBarBackground, true)
    excludeTarget(R.id.action_bar_container, true)
}
```

**Comment by DanteAndroid** [comment]
I still encounter a flash with TabsLayout
